// <auto-generated />
using System;
using Airport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Airport.Migrations
{
    [DbContext(typeof(AppEFContext))]
    partial class AppEFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Airport.Data.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ArrivalTo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DepartureFrom")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Flight");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalDate = new DateTime(2021, 10, 30, 22, 42, 33, 279, DateTimeKind.Local).AddTicks(5188),
                            ArrivalTo = "Port Georgette",
                            DepartureDate = new DateTime(2021, 10, 27, 11, 17, 19, 851, DateTimeKind.Local).AddTicks(5188),
                            DepartureFrom = "Willton",
                            Number = "SMH0"
                        },
                        new
                        {
                            Id = 2,
                            ArrivalDate = new DateTime(2021, 4, 20, 20, 7, 19, 659, DateTimeKind.Local).AddTicks(582),
                            ArrivalTo = "Lake Lamontchester",
                            DepartureDate = new DateTime(2021, 4, 20, 17, 54, 1, 619, DateTimeKind.Local).AddTicks(582),
                            DepartureFrom = "Brekkeshire",
                            Number = "YNB1"
                        },
                        new
                        {
                            Id = 3,
                            ArrivalDate = new DateTime(2021, 6, 24, 15, 4, 23, 363, DateTimeKind.Local).AddTicks(5593),
                            ArrivalTo = "Wendellport",
                            DepartureDate = new DateTime(2021, 6, 20, 9, 51, 55, 579, DateTimeKind.Local).AddTicks(5593),
                            DepartureFrom = "Kohlerhaven",
                            Number = "VAN2"
                        },
                        new
                        {
                            Id = 4,
                            ArrivalDate = new DateTime(2022, 7, 13, 7, 20, 49, 276, DateTimeKind.Local).AddTicks(1175),
                            ArrivalTo = "New Terence",
                            DepartureDate = new DateTime(2022, 7, 7, 12, 46, 19, 913, DateTimeKind.Local).AddTicks(1175),
                            DepartureFrom = "Lake Melyssa",
                            Number = "OQN3"
                        },
                        new
                        {
                            Id = 5,
                            ArrivalDate = new DateTime(2022, 6, 20, 12, 48, 18, 618, DateTimeKind.Local).AddTicks(982),
                            ArrivalTo = "Beckerview",
                            DepartureDate = new DateTime(2022, 6, 17, 10, 51, 18, 455, DateTimeKind.Local).AddTicks(982),
                            DepartureFrom = "Jerdeshire",
                            Number = "ADD4"
                        },
                        new
                        {
                            Id = 6,
                            ArrivalDate = new DateTime(2021, 10, 18, 1, 42, 28, 57, DateTimeKind.Local).AddTicks(4267),
                            ArrivalTo = "Jamesonland",
                            DepartureDate = new DateTime(2021, 10, 15, 12, 7, 18, 891, DateTimeKind.Local).AddTicks(4267),
                            DepartureFrom = "East Bertrandfort",
                            Number = "RVZ5"
                        },
                        new
                        {
                            Id = 7,
                            ArrivalDate = new DateTime(2021, 9, 11, 23, 26, 6, 23, DateTimeKind.Local).AddTicks(5028),
                            ArrivalTo = "Skilesbury",
                            DepartureDate = new DateTime(2021, 9, 2, 20, 0, 34, 413, DateTimeKind.Local).AddTicks(5028),
                            DepartureFrom = "Keelyton",
                            Number = "XJX6"
                        },
                        new
                        {
                            Id = 8,
                            ArrivalDate = new DateTime(2021, 8, 1, 23, 17, 59, 648, DateTimeKind.Local).AddTicks(1459),
                            ArrivalTo = "North Jamison",
                            DepartureDate = new DateTime(2021, 7, 24, 13, 49, 39, 869, DateTimeKind.Local).AddTicks(1459),
                            DepartureFrom = "Loyceview",
                            Number = "NJC7"
                        },
                        new
                        {
                            Id = 9,
                            ArrivalDate = new DateTime(2021, 8, 5, 7, 5, 35, 399, DateTimeKind.Local).AddTicks(8223),
                            ArrivalTo = "New Shanna",
                            DepartureDate = new DateTime(2021, 8, 2, 4, 14, 23, 262, DateTimeKind.Local).AddTicks(8223),
                            DepartureFrom = "Bayerbury",
                            Number = "AAO8"
                        },
                        new
                        {
                            Id = 10,
                            ArrivalDate = new DateTime(2021, 11, 23, 5, 5, 20, 23, DateTimeKind.Local).AddTicks(2933),
                            ArrivalTo = "Dooleyburgh",
                            DepartureDate = new DateTime(2021, 11, 18, 18, 35, 51, 379, DateTimeKind.Local).AddTicks(2933),
                            DepartureFrom = "North Elda",
                            Number = "UKV9"
                        },
                        new
                        {
                            Id = 11,
                            ArrivalDate = new DateTime(2021, 6, 16, 23, 31, 49, 432, DateTimeKind.Local).AddTicks(4145),
                            ArrivalTo = "Lake Arne",
                            DepartureDate = new DateTime(2021, 6, 8, 22, 33, 17, 596, DateTimeKind.Local).AddTicks(4145),
                            DepartureFrom = "New Alena",
                            Number = "XRF10"
                        },
                        new
                        {
                            Id = 12,
                            ArrivalDate = new DateTime(2021, 10, 26, 14, 22, 29, 312, DateTimeKind.Local).AddTicks(9975),
                            ArrivalTo = "West Marie",
                            DepartureDate = new DateTime(2021, 10, 20, 20, 48, 42, 516, DateTimeKind.Local).AddTicks(9975),
                            DepartureFrom = "Mandymouth",
                            Number = "IDF11"
                        },
                        new
                        {
                            Id = 13,
                            ArrivalDate = new DateTime(2021, 9, 18, 9, 37, 36, 671, DateTimeKind.Local).AddTicks(1051),
                            ArrivalTo = "Leanneport",
                            DepartureDate = new DateTime(2021, 9, 18, 0, 24, 44, 126, DateTimeKind.Local).AddTicks(1051),
                            DepartureFrom = "Royalville",
                            Number = "PNQ12"
                        },
                        new
                        {
                            Id = 14,
                            ArrivalDate = new DateTime(2021, 9, 10, 19, 10, 18, 911, DateTimeKind.Local).AddTicks(2401),
                            ArrivalTo = "West Wallacestad",
                            DepartureDate = new DateTime(2021, 9, 2, 13, 19, 44, 605, DateTimeKind.Local).AddTicks(2401),
                            DepartureFrom = "Kendallmouth",
                            Number = "NCP13"
                        },
                        new
                        {
                            Id = 15,
                            ArrivalDate = new DateTime(2021, 7, 6, 19, 32, 19, 259, DateTimeKind.Local).AddTicks(6367),
                            ArrivalTo = "South Orenton",
                            DepartureDate = new DateTime(2021, 6, 28, 2, 8, 40, 237, DateTimeKind.Local).AddTicks(6367),
                            DepartureFrom = "Wilmerbury",
                            Number = "DCF14"
                        },
                        new
                        {
                            Id = 16,
                            ArrivalDate = new DateTime(2022, 7, 6, 2, 12, 24, 389, DateTimeKind.Local).AddTicks(3638),
                            ArrivalTo = "East Myronshire",
                            DepartureDate = new DateTime(2022, 7, 3, 11, 34, 48, 14, DateTimeKind.Local).AddTicks(3638),
                            DepartureFrom = "Chelseastad",
                            Number = "FUN15"
                        },
                        new
                        {
                            Id = 17,
                            ArrivalDate = new DateTime(2021, 11, 10, 2, 36, 26, 689, DateTimeKind.Local).AddTicks(1473),
                            ArrivalTo = "West Willow",
                            DepartureDate = new DateTime(2021, 11, 9, 2, 44, 30, 549, DateTimeKind.Local).AddTicks(1473),
                            DepartureFrom = "West Felixview",
                            Number = "QWQ16"
                        },
                        new
                        {
                            Id = 18,
                            ArrivalDate = new DateTime(2022, 6, 19, 14, 42, 49, 730, DateTimeKind.Local).AddTicks(1313),
                            ArrivalTo = "East Berniceburgh",
                            DepartureDate = new DateTime(2022, 6, 10, 19, 34, 10, 15, DateTimeKind.Local).AddTicks(1313),
                            DepartureFrom = "Henrietteland",
                            Number = "INI17"
                        },
                        new
                        {
                            Id = 19,
                            ArrivalDate = new DateTime(2022, 4, 5, 23, 59, 40, 420, DateTimeKind.Local).AddTicks(7066),
                            ArrivalTo = "Trantowview",
                            DepartureDate = new DateTime(2022, 4, 1, 11, 58, 50, 86, DateTimeKind.Local).AddTicks(7066),
                            DepartureFrom = "West Riley",
                            Number = "JGE18"
                        },
                        new
                        {
                            Id = 20,
                            ArrivalDate = new DateTime(2021, 11, 26, 8, 1, 51, 809, DateTimeKind.Local).AddTicks(5350),
                            ArrivalTo = "Fayfurt",
                            DepartureDate = new DateTime(2021, 11, 24, 20, 9, 53, 676, DateTimeKind.Local).AddTicks(5350),
                            DepartureFrom = "North Marleneside",
                            Number = "SNN19"
                        });
                });

            modelBuilder.Entity("Airport.Data.Entities.FlightTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("FlightTicket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 16,
                            TicketId = 1
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 19,
                            TicketId = 2
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 1,
                            TicketId = 3
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 14,
                            TicketId = 4
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 14,
                            TicketId = 5
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 5,
                            TicketId = 6
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 1,
                            TicketId = 7
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 17,
                            TicketId = 8
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 6,
                            TicketId = 9
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 16,
                            TicketId = 10
                        },
                        new
                        {
                            Id = 11,
                            FlightId = 19,
                            TicketId = 11
                        },
                        new
                        {
                            Id = 12,
                            FlightId = 15,
                            TicketId = 12
                        },
                        new
                        {
                            Id = 13,
                            FlightId = 10,
                            TicketId = 13
                        },
                        new
                        {
                            Id = 14,
                            FlightId = 15,
                            TicketId = 14
                        },
                        new
                        {
                            Id = 15,
                            FlightId = 16,
                            TicketId = 15
                        },
                        new
                        {
                            Id = 16,
                            FlightId = 3,
                            TicketId = 16
                        },
                        new
                        {
                            Id = 17,
                            FlightId = 6,
                            TicketId = 17
                        },
                        new
                        {
                            Id = 18,
                            FlightId = 18,
                            TicketId = 18
                        },
                        new
                        {
                            Id = 19,
                            FlightId = 19,
                            TicketId = 19
                        },
                        new
                        {
                            Id = 20,
                            FlightId = 1,
                            TicketId = 20
                        },
                        new
                        {
                            Id = 21,
                            FlightId = 7,
                            TicketId = 21
                        },
                        new
                        {
                            Id = 22,
                            FlightId = 17,
                            TicketId = 22
                        },
                        new
                        {
                            Id = 23,
                            FlightId = 7,
                            TicketId = 23
                        },
                        new
                        {
                            Id = 24,
                            FlightId = 6,
                            TicketId = 24
                        },
                        new
                        {
                            Id = 25,
                            FlightId = 13,
                            TicketId = 25
                        },
                        new
                        {
                            Id = 26,
                            FlightId = 15,
                            TicketId = 26
                        },
                        new
                        {
                            Id = 27,
                            FlightId = 4,
                            TicketId = 27
                        },
                        new
                        {
                            Id = 28,
                            FlightId = 14,
                            TicketId = 28
                        },
                        new
                        {
                            Id = 29,
                            FlightId = 16,
                            TicketId = 29
                        },
                        new
                        {
                            Id = 30,
                            FlightId = 4,
                            TicketId = 30
                        },
                        new
                        {
                            Id = 31,
                            FlightId = 19,
                            TicketId = 31
                        },
                        new
                        {
                            Id = 32,
                            FlightId = 6,
                            TicketId = 32
                        },
                        new
                        {
                            Id = 33,
                            FlightId = 6,
                            TicketId = 33
                        },
                        new
                        {
                            Id = 34,
                            FlightId = 16,
                            TicketId = 34
                        },
                        new
                        {
                            Id = 35,
                            FlightId = 7,
                            TicketId = 35
                        },
                        new
                        {
                            Id = 36,
                            FlightId = 18,
                            TicketId = 36
                        },
                        new
                        {
                            Id = 37,
                            FlightId = 9,
                            TicketId = 37
                        },
                        new
                        {
                            Id = 38,
                            FlightId = 10,
                            TicketId = 38
                        },
                        new
                        {
                            Id = 39,
                            FlightId = 7,
                            TicketId = 39
                        },
                        new
                        {
                            Id = 40,
                            FlightId = 4,
                            TicketId = 40
                        },
                        new
                        {
                            Id = 41,
                            FlightId = 12,
                            TicketId = 41
                        },
                        new
                        {
                            Id = 42,
                            FlightId = 11,
                            TicketId = 42
                        },
                        new
                        {
                            Id = 43,
                            FlightId = 7,
                            TicketId = 43
                        },
                        new
                        {
                            Id = 44,
                            FlightId = 19,
                            TicketId = 44
                        },
                        new
                        {
                            Id = 45,
                            FlightId = 12,
                            TicketId = 45
                        },
                        new
                        {
                            Id = 46,
                            FlightId = 10,
                            TicketId = 46
                        },
                        new
                        {
                            Id = 47,
                            FlightId = 4,
                            TicketId = 47
                        },
                        new
                        {
                            Id = 48,
                            FlightId = 18,
                            TicketId = 48
                        },
                        new
                        {
                            Id = 49,
                            FlightId = 8,
                            TicketId = 49
                        },
                        new
                        {
                            Id = 50,
                            FlightId = 14,
                            TicketId = 50
                        },
                        new
                        {
                            Id = 51,
                            FlightId = 14,
                            TicketId = 51
                        },
                        new
                        {
                            Id = 52,
                            FlightId = 15,
                            TicketId = 52
                        },
                        new
                        {
                            Id = 53,
                            FlightId = 7,
                            TicketId = 53
                        },
                        new
                        {
                            Id = 54,
                            FlightId = 3,
                            TicketId = 54
                        },
                        new
                        {
                            Id = 55,
                            FlightId = 17,
                            TicketId = 55
                        },
                        new
                        {
                            Id = 56,
                            FlightId = 18,
                            TicketId = 56
                        },
                        new
                        {
                            Id = 57,
                            FlightId = 12,
                            TicketId = 57
                        },
                        new
                        {
                            Id = 58,
                            FlightId = 14,
                            TicketId = 58
                        },
                        new
                        {
                            Id = 59,
                            FlightId = 2,
                            TicketId = 59
                        },
                        new
                        {
                            Id = 60,
                            FlightId = 19,
                            TicketId = 60
                        },
                        new
                        {
                            Id = 61,
                            FlightId = 2,
                            TicketId = 61
                        },
                        new
                        {
                            Id = 62,
                            FlightId = 6,
                            TicketId = 62
                        },
                        new
                        {
                            Id = 63,
                            FlightId = 2,
                            TicketId = 63
                        },
                        new
                        {
                            Id = 64,
                            FlightId = 3,
                            TicketId = 64
                        },
                        new
                        {
                            Id = 65,
                            FlightId = 17,
                            TicketId = 65
                        },
                        new
                        {
                            Id = 66,
                            FlightId = 14,
                            TicketId = 66
                        },
                        new
                        {
                            Id = 67,
                            FlightId = 9,
                            TicketId = 67
                        },
                        new
                        {
                            Id = 68,
                            FlightId = 14,
                            TicketId = 68
                        },
                        new
                        {
                            Id = 69,
                            FlightId = 8,
                            TicketId = 69
                        },
                        new
                        {
                            Id = 70,
                            FlightId = 18,
                            TicketId = 70
                        },
                        new
                        {
                            Id = 71,
                            FlightId = 13,
                            TicketId = 71
                        },
                        new
                        {
                            Id = 72,
                            FlightId = 16,
                            TicketId = 72
                        },
                        new
                        {
                            Id = 73,
                            FlightId = 11,
                            TicketId = 73
                        },
                        new
                        {
                            Id = 74,
                            FlightId = 15,
                            TicketId = 74
                        },
                        new
                        {
                            Id = 75,
                            FlightId = 9,
                            TicketId = 75
                        },
                        new
                        {
                            Id = 76,
                            FlightId = 16,
                            TicketId = 76
                        },
                        new
                        {
                            Id = 77,
                            FlightId = 10,
                            TicketId = 77
                        },
                        new
                        {
                            Id = 78,
                            FlightId = 8,
                            TicketId = 78
                        },
                        new
                        {
                            Id = 79,
                            FlightId = 14,
                            TicketId = 79
                        },
                        new
                        {
                            Id = 80,
                            FlightId = 4,
                            TicketId = 80
                        },
                        new
                        {
                            Id = 81,
                            FlightId = 11,
                            TicketId = 81
                        },
                        new
                        {
                            Id = 82,
                            FlightId = 6,
                            TicketId = 82
                        },
                        new
                        {
                            Id = 83,
                            FlightId = 7,
                            TicketId = 83
                        },
                        new
                        {
                            Id = 84,
                            FlightId = 3,
                            TicketId = 84
                        },
                        new
                        {
                            Id = 85,
                            FlightId = 10,
                            TicketId = 85
                        },
                        new
                        {
                            Id = 86,
                            FlightId = 5,
                            TicketId = 86
                        },
                        new
                        {
                            Id = 87,
                            FlightId = 18,
                            TicketId = 87
                        },
                        new
                        {
                            Id = 88,
                            FlightId = 4,
                            TicketId = 88
                        },
                        new
                        {
                            Id = 89,
                            FlightId = 19,
                            TicketId = 89
                        },
                        new
                        {
                            Id = 90,
                            FlightId = 9,
                            TicketId = 90
                        },
                        new
                        {
                            Id = 91,
                            FlightId = 7,
                            TicketId = 91
                        },
                        new
                        {
                            Id = 92,
                            FlightId = 15,
                            TicketId = 92
                        },
                        new
                        {
                            Id = 93,
                            FlightId = 9,
                            TicketId = 93
                        },
                        new
                        {
                            Id = 94,
                            FlightId = 7,
                            TicketId = 94
                        },
                        new
                        {
                            Id = 95,
                            FlightId = 3,
                            TicketId = 95
                        },
                        new
                        {
                            Id = 96,
                            FlightId = 6,
                            TicketId = 96
                        },
                        new
                        {
                            Id = 97,
                            FlightId = 10,
                            TicketId = 97
                        },
                        new
                        {
                            Id = 98,
                            FlightId = 5,
                            TicketId = 98
                        },
                        new
                        {
                            Id = 99,
                            FlightId = 3,
                            TicketId = 99
                        },
                        new
                        {
                            Id = 100,
                            FlightId = 17,
                            TicketId = 100
                        });
                });

            modelBuilder.Entity("Airport.Data.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PassengerFullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PassengerPassport")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyDate = new DateTime(2021, 2, 16, 16, 55, 28, 782, DateTimeKind.Local).AddTicks(8804),
                            IsActive = true,
                            Number = "LUJPL20",
                            PassengerFullName = "Karina Bruen",
                            PassengerPassport = "LUUFVDY20",
                            Place = "H20",
                            Price = 265.71m
                        },
                        new
                        {
                            Id = 2,
                            BuyDate = new DateTime(2021, 7, 5, 0, 45, 42, 993, DateTimeKind.Local).AddTicks(7087),
                            IsActive = true,
                            Number = "LZZHL21",
                            PassengerFullName = "Tremayne Littel",
                            PassengerPassport = "EERMAAP21",
                            Place = "H21",
                            Price = 257.68m
                        },
                        new
                        {
                            Id = 3,
                            BuyDate = new DateTime(2020, 12, 30, 17, 5, 30, 647, DateTimeKind.Local).AddTicks(406),
                            IsActive = true,
                            Number = "VAQOH22",
                            PassengerFullName = "Otto Heaney",
                            PassengerPassport = "LKHVYJX22",
                            Place = "D22",
                            Price = 339.38m
                        },
                        new
                        {
                            Id = 4,
                            BuyDate = new DateTime(2021, 8, 4, 0, 50, 4, 194, DateTimeKind.Local).AddTicks(8654),
                            IsActive = false,
                            Number = "BZEVT23",
                            PassengerFullName = "Marcelle Lemke",
                            PassengerPassport = "PRJBJDZ23",
                            Place = "G23",
                            Price = 148.00m
                        },
                        new
                        {
                            Id = 5,
                            BuyDate = new DateTime(2021, 10, 21, 17, 39, 46, 779, DateTimeKind.Local).AddTicks(5313),
                            IsActive = false,
                            Number = "NKEWM24",
                            PassengerFullName = "Rhett Mann",
                            PassengerPassport = "OLNANSD24",
                            Place = "B24",
                            Price = 283.22m
                        },
                        new
                        {
                            Id = 6,
                            BuyDate = new DateTime(2021, 4, 5, 9, 49, 56, 986, DateTimeKind.Local).AddTicks(5899),
                            IsActive = true,
                            Number = "KSHZO25",
                            PassengerFullName = "Abby Schmidt",
                            PassengerPassport = "OCKVNLR25",
                            Place = "D25",
                            Price = 33.60m
                        },
                        new
                        {
                            Id = 7,
                            BuyDate = new DateTime(2021, 7, 25, 10, 17, 15, 823, DateTimeKind.Local).AddTicks(5865),
                            IsActive = true,
                            Number = "ZQYYD26",
                            PassengerFullName = "Harvey Bashirian",
                            PassengerPassport = "YQDJCWZ26",
                            Place = "J26",
                            Price = 10.62m
                        },
                        new
                        {
                            Id = 8,
                            BuyDate = new DateTime(2021, 5, 10, 7, 35, 59, 828, DateTimeKind.Local).AddTicks(8109),
                            IsActive = true,
                            Number = "UBUJM27",
                            PassengerFullName = "Korbin Batz",
                            PassengerPassport = "RJMNWZV27",
                            Place = "C27",
                            Price = 484.53m
                        },
                        new
                        {
                            Id = 9,
                            BuyDate = new DateTime(2021, 2, 7, 4, 30, 44, 525, DateTimeKind.Local).AddTicks(5823),
                            IsActive = false,
                            Number = "AAWDG28",
                            PassengerFullName = "Hassan Gutmann",
                            PassengerPassport = "JCZZIRI28",
                            Place = "L28",
                            Price = 296.26m
                        },
                        new
                        {
                            Id = 10,
                            BuyDate = new DateTime(2021, 9, 11, 8, 49, 57, 837, DateTimeKind.Local).AddTicks(3158),
                            IsActive = true,
                            Number = "QOHMR29",
                            PassengerFullName = "Pascale Kihn",
                            PassengerPassport = "RPXQAYI29",
                            Place = "J29",
                            Price = 771.59m
                        },
                        new
                        {
                            Id = 11,
                            BuyDate = new DateTime(2020, 11, 23, 18, 7, 55, 470, DateTimeKind.Local).AddTicks(7292),
                            IsActive = true,
                            Number = "RDVYM30",
                            PassengerFullName = "Shirley Hills",
                            PassengerPassport = "UUAIWPH30",
                            Place = "J30",
                            Price = 762.19m
                        },
                        new
                        {
                            Id = 12,
                            BuyDate = new DateTime(2021, 10, 18, 18, 42, 1, 138, DateTimeKind.Local).AddTicks(1316),
                            IsActive = false,
                            Number = "DBIFP31",
                            PassengerFullName = "Eloise Orn",
                            PassengerPassport = "FZILQJV31",
                            Place = "J31",
                            Price = 178.57m
                        },
                        new
                        {
                            Id = 13,
                            BuyDate = new DateTime(2021, 1, 27, 9, 38, 27, 820, DateTimeKind.Local).AddTicks(6852),
                            IsActive = true,
                            Number = "BBKMO32",
                            PassengerFullName = "Tyree Considine",
                            PassengerPassport = "GSOXCRW32",
                            Place = "I32",
                            Price = 208.69m
                        },
                        new
                        {
                            Id = 14,
                            BuyDate = new DateTime(2021, 10, 4, 0, 2, 39, 810, DateTimeKind.Local).AddTicks(7221),
                            IsActive = false,
                            Number = "BHMOP33",
                            PassengerFullName = "Keshawn Predovic",
                            PassengerPassport = "JDQUKZH33",
                            Place = "C33",
                            Price = 270.01m
                        },
                        new
                        {
                            Id = 15,
                            BuyDate = new DateTime(2020, 12, 13, 8, 34, 10, 529, DateTimeKind.Local).AddTicks(2650),
                            IsActive = true,
                            Number = "TFDKP34",
                            PassengerFullName = "Xzavier Barton",
                            PassengerPassport = "KMXGNPM34",
                            Place = "B34",
                            Price = 950.40m
                        },
                        new
                        {
                            Id = 16,
                            BuyDate = new DateTime(2020, 12, 27, 23, 54, 7, 984, DateTimeKind.Local).AddTicks(3958),
                            IsActive = false,
                            Number = "ZDUMU35",
                            PassengerFullName = "Daisha Franecki",
                            PassengerPassport = "WVCOXWT35",
                            Place = "B35",
                            Price = 309.17m
                        },
                        new
                        {
                            Id = 17,
                            BuyDate = new DateTime(2021, 4, 13, 14, 29, 5, 256, DateTimeKind.Local).AddTicks(2194),
                            IsActive = false,
                            Number = "PUBVA36",
                            PassengerFullName = "Armando Ratke",
                            PassengerPassport = "PXCMWWH36",
                            Place = "I36",
                            Price = 438.84m
                        },
                        new
                        {
                            Id = 18,
                            BuyDate = new DateTime(2021, 1, 24, 12, 6, 54, 824, DateTimeKind.Local).AddTicks(1136),
                            IsActive = true,
                            Number = "LULEG37",
                            PassengerFullName = "Minnie Wyman",
                            PassengerPassport = "LPXNZKV37",
                            Place = "B37",
                            Price = 428.49m
                        },
                        new
                        {
                            Id = 19,
                            BuyDate = new DateTime(2021, 8, 2, 11, 16, 2, 1, DateTimeKind.Local).AddTicks(6574),
                            IsActive = true,
                            Number = "VVCCA38",
                            PassengerFullName = "Mike Rice",
                            PassengerPassport = "AABUMJT38",
                            Place = "F38",
                            Price = 535.52m
                        },
                        new
                        {
                            Id = 20,
                            BuyDate = new DateTime(2021, 3, 10, 5, 55, 2, 0, DateTimeKind.Local).AddTicks(6964),
                            IsActive = true,
                            Number = "MOPUF39",
                            PassengerFullName = "Gavin Volkman",
                            PassengerPassport = "WXYTVGX39",
                            Place = "K39",
                            Price = 770.14m
                        },
                        new
                        {
                            Id = 21,
                            BuyDate = new DateTime(2021, 4, 14, 18, 4, 47, 806, DateTimeKind.Local).AddTicks(506),
                            IsActive = false,
                            Number = "YXYFI40",
                            PassengerFullName = "Anita Wolf",
                            PassengerPassport = "QWNZEZV40",
                            Place = "B40",
                            Price = 219.60m
                        },
                        new
                        {
                            Id = 22,
                            BuyDate = new DateTime(2021, 9, 12, 1, 7, 58, 111, DateTimeKind.Local).AddTicks(7106),
                            IsActive = true,
                            Number = "ZOVVE41",
                            PassengerFullName = "Chelsie Okuneva",
                            PassengerPassport = "FSNTFLB41",
                            Place = "G41",
                            Price = 273.02m
                        },
                        new
                        {
                            Id = 23,
                            BuyDate = new DateTime(2021, 7, 4, 10, 58, 47, 325, DateTimeKind.Local).AddTicks(8003),
                            IsActive = false,
                            Number = "MXCCX42",
                            PassengerFullName = "Vito Baumbach",
                            PassengerPassport = "AJUVBDO42",
                            Place = "C42",
                            Price = 749.67m
                        },
                        new
                        {
                            Id = 24,
                            BuyDate = new DateTime(2021, 5, 9, 6, 6, 1, 487, DateTimeKind.Local).AddTicks(5437),
                            IsActive = false,
                            Number = "CVSPM43",
                            PassengerFullName = "Toni Johnson",
                            PassengerPassport = "EYFTQRR43",
                            Place = "C43",
                            Price = 226.46m
                        },
                        new
                        {
                            Id = 25,
                            BuyDate = new DateTime(2021, 1, 23, 6, 26, 32, 321, DateTimeKind.Local).AddTicks(2128),
                            IsActive = false,
                            Number = "MJUAP44",
                            PassengerFullName = "Lizeth Rutherford",
                            PassengerPassport = "OFCGWVP44",
                            Place = "D44",
                            Price = 719.51m
                        },
                        new
                        {
                            Id = 26,
                            BuyDate = new DateTime(2021, 1, 7, 14, 34, 36, 829, DateTimeKind.Local).AddTicks(3249),
                            IsActive = false,
                            Number = "ZYAXJ45",
                            PassengerFullName = "Amber Gaylord",
                            PassengerPassport = "YGLSVMZ45",
                            Place = "C45",
                            Price = 125.19m
                        },
                        new
                        {
                            Id = 27,
                            BuyDate = new DateTime(2021, 1, 8, 3, 33, 56, 519, DateTimeKind.Local).AddTicks(6417),
                            IsActive = true,
                            Number = "YZRHL46",
                            PassengerFullName = "Elliott Emard",
                            PassengerPassport = "UBCPHZR46",
                            Place = "K46",
                            Price = 188.99m
                        },
                        new
                        {
                            Id = 28,
                            BuyDate = new DateTime(2021, 3, 21, 6, 15, 45, 987, DateTimeKind.Local).AddTicks(6404),
                            IsActive = false,
                            Number = "JHAHK47",
                            PassengerFullName = "Jalen Barrows",
                            PassengerPassport = "MPCOHDS47",
                            Place = "J47",
                            Price = 61.23m
                        },
                        new
                        {
                            Id = 29,
                            BuyDate = new DateTime(2020, 12, 28, 10, 53, 17, 90, DateTimeKind.Local).AddTicks(5040),
                            IsActive = true,
                            Number = "KYVWW48",
                            PassengerFullName = "Sadie Dare",
                            PassengerPassport = "MCUHVNL48",
                            Place = "C48",
                            Price = 43.36m
                        },
                        new
                        {
                            Id = 30,
                            BuyDate = new DateTime(2021, 6, 15, 13, 32, 28, 391, DateTimeKind.Local).AddTicks(4274),
                            IsActive = true,
                            Number = "CWPYU49",
                            PassengerFullName = "Marlon Krajcik",
                            PassengerPassport = "YURQXSN49",
                            Place = "C49",
                            Price = 334.61m
                        },
                        new
                        {
                            Id = 31,
                            BuyDate = new DateTime(2021, 2, 4, 23, 36, 22, 440, DateTimeKind.Local).AddTicks(2369),
                            IsActive = true,
                            Number = "ORGGD50",
                            PassengerFullName = "Lucienne Kemmer",
                            PassengerPassport = "EHELWFT50",
                            Place = "F50",
                            Price = 344.82m
                        },
                        new
                        {
                            Id = 32,
                            BuyDate = new DateTime(2021, 10, 21, 3, 1, 8, 445, DateTimeKind.Local).AddTicks(8657),
                            IsActive = false,
                            Number = "OVSMJ51",
                            PassengerFullName = "Brannon Paucek",
                            PassengerPassport = "KLOYMDM51",
                            Place = "J51",
                            Price = 245.19m
                        },
                        new
                        {
                            Id = 33,
                            BuyDate = new DateTime(2021, 4, 30, 0, 40, 2, 112, DateTimeKind.Local).AddTicks(9800),
                            IsActive = false,
                            Number = "ENQGU52",
                            PassengerFullName = "Caroline Strosin",
                            PassengerPassport = "VZDSMMJ52",
                            Place = "I52",
                            Price = 210.02m
                        },
                        new
                        {
                            Id = 34,
                            BuyDate = new DateTime(2020, 11, 18, 10, 36, 48, 941, DateTimeKind.Local).AddTicks(8641),
                            IsActive = true,
                            Number = "CDVQA53",
                            PassengerFullName = "Rowan Fahey",
                            PassengerPassport = "IWRJZHA53",
                            Place = "J53",
                            Price = 624.62m
                        },
                        new
                        {
                            Id = 35,
                            BuyDate = new DateTime(2021, 5, 11, 15, 10, 24, 185, DateTimeKind.Local).AddTicks(7416),
                            IsActive = false,
                            Number = "GROTQ54",
                            PassengerFullName = "Jayne Kessler",
                            PassengerPassport = "DXLOIZA54",
                            Place = "L54",
                            Price = 155.90m
                        },
                        new
                        {
                            Id = 36,
                            BuyDate = new DateTime(2021, 1, 25, 20, 50, 48, 232, DateTimeKind.Local).AddTicks(3097),
                            IsActive = true,
                            Number = "YNSEN55",
                            PassengerFullName = "Shaylee Bauch",
                            PassengerPassport = "IIIWBLR55",
                            Place = "B55",
                            Price = 917.39m
                        },
                        new
                        {
                            Id = 37,
                            BuyDate = new DateTime(2021, 2, 2, 7, 55, 31, 247, DateTimeKind.Local).AddTicks(460),
                            IsActive = false,
                            Number = "AFIQG56",
                            PassengerFullName = "Cindy Zboncak",
                            PassengerPassport = "BKNMSYM56",
                            Place = "D56",
                            Price = 370.95m
                        },
                        new
                        {
                            Id = 38,
                            BuyDate = new DateTime(2020, 11, 9, 15, 1, 57, 593, DateTimeKind.Local).AddTicks(7239),
                            IsActive = true,
                            Number = "OVCNK57",
                            PassengerFullName = "Esteban Leffler",
                            PassengerPassport = "SJNMEVK57",
                            Place = "L57",
                            Price = 221.29m
                        },
                        new
                        {
                            Id = 39,
                            BuyDate = new DateTime(2021, 5, 3, 20, 14, 3, 10, DateTimeKind.Local).AddTicks(1755),
                            IsActive = false,
                            Number = "SXKDW58",
                            PassengerFullName = "Eda Hills",
                            PassengerPassport = "GVUPJOE58",
                            Place = "F58",
                            Price = 209.83m
                        },
                        new
                        {
                            Id = 40,
                            BuyDate = new DateTime(2021, 10, 21, 11, 51, 34, 587, DateTimeKind.Local).AddTicks(6288),
                            IsActive = true,
                            Number = "DFJAV59",
                            PassengerFullName = "Donnell Runte",
                            PassengerPassport = "LOHDLHN59",
                            Place = "L59",
                            Price = 633.71m
                        },
                        new
                        {
                            Id = 41,
                            BuyDate = new DateTime(2021, 8, 24, 16, 25, 43, 491, DateTimeKind.Local).AddTicks(145),
                            IsActive = false,
                            Number = "UPBJY60",
                            PassengerFullName = "Lisa Paucek",
                            PassengerPassport = "PZKEJYO60",
                            Place = "E60",
                            Price = 932.10m
                        },
                        new
                        {
                            Id = 42,
                            BuyDate = new DateTime(2020, 11, 16, 5, 59, 32, 901, DateTimeKind.Local).AddTicks(3182),
                            IsActive = false,
                            Number = "SGJGB61",
                            PassengerFullName = "Ara Batz",
                            PassengerPassport = "BDGVSRW61",
                            Place = "K61",
                            Price = 235.21m
                        },
                        new
                        {
                            Id = 43,
                            BuyDate = new DateTime(2020, 12, 20, 9, 11, 7, 4, DateTimeKind.Local).AddTicks(3001),
                            IsActive = false,
                            Number = "CTYKP62",
                            PassengerFullName = "Brenna Brown",
                            PassengerPassport = "EURKQXU62",
                            Place = "L62",
                            Price = 44.83m
                        },
                        new
                        {
                            Id = 44,
                            BuyDate = new DateTime(2021, 1, 8, 16, 55, 36, 141, DateTimeKind.Local).AddTicks(9641),
                            IsActive = true,
                            Number = "ZZBOQ63",
                            PassengerFullName = "Lauren Bradtke",
                            PassengerPassport = "JOVZIPT63",
                            Place = "D63",
                            Price = 929.67m
                        },
                        new
                        {
                            Id = 45,
                            BuyDate = new DateTime(2020, 11, 28, 12, 40, 2, 534, DateTimeKind.Local).AddTicks(5000),
                            IsActive = false,
                            Number = "EFNJK64",
                            PassengerFullName = "Dee O'Keefe",
                            PassengerPassport = "DRRYIXI64",
                            Place = "E64",
                            Price = 856.94m
                        },
                        new
                        {
                            Id = 46,
                            BuyDate = new DateTime(2021, 5, 29, 21, 57, 18, 246, DateTimeKind.Local).AddTicks(6421),
                            IsActive = true,
                            Number = "CBOHE65",
                            PassengerFullName = "Katherine Gorczany",
                            PassengerPassport = "UUGUFCU65",
                            Place = "A65",
                            Price = 902.78m
                        },
                        new
                        {
                            Id = 47,
                            BuyDate = new DateTime(2021, 10, 22, 22, 12, 37, 433, DateTimeKind.Local).AddTicks(9083),
                            IsActive = true,
                            Number = "BCDLU66",
                            PassengerFullName = "Monroe Senger",
                            PassengerPassport = "DPJIORN66",
                            Place = "J66",
                            Price = 57.18m
                        },
                        new
                        {
                            Id = 48,
                            BuyDate = new DateTime(2021, 8, 20, 4, 36, 6, 37, DateTimeKind.Local).AddTicks(4732),
                            IsActive = true,
                            Number = "HPKLP67",
                            PassengerFullName = "Zaria Heathcote",
                            PassengerPassport = "KQFNFRU67",
                            Place = "A67",
                            Price = 794.35m
                        },
                        new
                        {
                            Id = 49,
                            BuyDate = new DateTime(2021, 2, 7, 22, 5, 36, 767, DateTimeKind.Local).AddTicks(5304),
                            IsActive = false,
                            Number = "FBREW68",
                            PassengerFullName = "Francesco Gislason",
                            PassengerPassport = "MLQGTCI68",
                            Place = "K68",
                            Price = 131.28m
                        },
                        new
                        {
                            Id = 50,
                            BuyDate = new DateTime(2021, 10, 8, 3, 28, 32, 464, DateTimeKind.Local).AddTicks(2255),
                            IsActive = false,
                            Number = "CJIBD69",
                            PassengerFullName = "Jess Marks",
                            PassengerPassport = "JBWNSTC69",
                            Place = "D69",
                            Price = 670.81m
                        },
                        new
                        {
                            Id = 51,
                            BuyDate = new DateTime(2021, 4, 3, 7, 13, 35, 939, DateTimeKind.Local).AddTicks(2816),
                            IsActive = false,
                            Number = "ZOLHC70",
                            PassengerFullName = "Leta Jones",
                            PassengerPassport = "RAILNXN70",
                            Place = "I70",
                            Price = 969.89m
                        },
                        new
                        {
                            Id = 52,
                            BuyDate = new DateTime(2021, 4, 8, 11, 11, 57, 661, DateTimeKind.Local).AddTicks(8010),
                            IsActive = false,
                            Number = "PIOXI71",
                            PassengerFullName = "Tamia Doyle",
                            PassengerPassport = "FRUIIUF71",
                            Place = "D71",
                            Price = 531.93m
                        },
                        new
                        {
                            Id = 53,
                            BuyDate = new DateTime(2021, 9, 5, 17, 27, 1, 509, DateTimeKind.Local).AddTicks(4151),
                            IsActive = false,
                            Number = "EMKXX72",
                            PassengerFullName = "Edythe Jakubowski",
                            PassengerPassport = "MCCYCLQ72",
                            Place = "F72",
                            Price = 416.96m
                        },
                        new
                        {
                            Id = 54,
                            BuyDate = new DateTime(2021, 2, 11, 13, 57, 13, 480, DateTimeKind.Local).AddTicks(583),
                            IsActive = false,
                            Number = "EOSLS73",
                            PassengerFullName = "Daija DuBuque",
                            PassengerPassport = "XANXBLB73",
                            Place = "E73",
                            Price = 821.57m
                        },
                        new
                        {
                            Id = 55,
                            BuyDate = new DateTime(2021, 7, 25, 16, 16, 45, 776, DateTimeKind.Local).AddTicks(5800),
                            IsActive = true,
                            Number = "KPLOZ74",
                            PassengerFullName = "Lambert Kreiger",
                            PassengerPassport = "XGDFIMD74",
                            Place = "A74",
                            Price = 217.76m
                        },
                        new
                        {
                            Id = 56,
                            BuyDate = new DateTime(2021, 10, 4, 12, 32, 19, 945, DateTimeKind.Local).AddTicks(9623),
                            IsActive = true,
                            Number = "QXEQQ75",
                            PassengerFullName = "Florian Zemlak",
                            PassengerPassport = "LXSTLEY75",
                            Place = "K75",
                            Price = 172.28m
                        },
                        new
                        {
                            Id = 57,
                            BuyDate = new DateTime(2021, 8, 14, 10, 23, 9, 460, DateTimeKind.Local).AddTicks(3774),
                            IsActive = false,
                            Number = "LGSJI76",
                            PassengerFullName = "Karen Muller",
                            PassengerPassport = "ULBISIS76",
                            Place = "B76",
                            Price = 614.70m
                        },
                        new
                        {
                            Id = 58,
                            BuyDate = new DateTime(2021, 5, 23, 5, 16, 26, 156, DateTimeKind.Local).AddTicks(2553),
                            IsActive = false,
                            Number = "WWWKO77",
                            PassengerFullName = "Kyleigh Schimmel",
                            PassengerPassport = "TQUYJEP77",
                            Place = "K77",
                            Price = 128.42m
                        },
                        new
                        {
                            Id = 59,
                            BuyDate = new DateTime(2021, 7, 27, 15, 47, 19, 928, DateTimeKind.Local).AddTicks(9665),
                            IsActive = false,
                            Number = "NTJPK78",
                            PassengerFullName = "Omari Donnelly",
                            PassengerPassport = "RMRTLLN78",
                            Place = "B78",
                            Price = 366.49m
                        },
                        new
                        {
                            Id = 60,
                            BuyDate = new DateTime(2021, 4, 25, 2, 19, 10, 191, DateTimeKind.Local).AddTicks(4272),
                            IsActive = true,
                            Number = "ZOERF79",
                            PassengerFullName = "Claudine Schowalter",
                            PassengerPassport = "EHHLEMH79",
                            Place = "D79",
                            Price = 611.87m
                        },
                        new
                        {
                            Id = 61,
                            BuyDate = new DateTime(2021, 7, 24, 12, 19, 59, 973, DateTimeKind.Local).AddTicks(3845),
                            IsActive = false,
                            Number = "EGPXC80",
                            PassengerFullName = "Annamarie Batz",
                            PassengerPassport = "EUOLHHG80",
                            Place = "E80",
                            Price = 227.78m
                        },
                        new
                        {
                            Id = 62,
                            BuyDate = new DateTime(2021, 3, 6, 3, 34, 48, 944, DateTimeKind.Local).AddTicks(1002),
                            IsActive = false,
                            Number = "FAIFP81",
                            PassengerFullName = "Caleb Conn",
                            PassengerPassport = "TJODIPJ81",
                            Place = "K81",
                            Price = 469.87m
                        },
                        new
                        {
                            Id = 63,
                            BuyDate = new DateTime(2021, 6, 24, 6, 1, 40, 683, DateTimeKind.Local).AddTicks(4396),
                            IsActive = false,
                            Number = "JMZLR82",
                            PassengerFullName = "Hobart Homenick",
                            PassengerPassport = "UTWBEJS82",
                            Place = "B82",
                            Price = 632.91m
                        },
                        new
                        {
                            Id = 64,
                            BuyDate = new DateTime(2021, 9, 16, 3, 55, 37, 468, DateTimeKind.Local).AddTicks(7395),
                            IsActive = false,
                            Number = "HAYHQ83",
                            PassengerFullName = "Loren Balistreri",
                            PassengerPassport = "BCGVLUB83",
                            Place = "E83",
                            Price = 83.38m
                        },
                        new
                        {
                            Id = 65,
                            BuyDate = new DateTime(2021, 5, 2, 15, 44, 43, 494, DateTimeKind.Local).AddTicks(7861),
                            IsActive = true,
                            Number = "ARTNI84",
                            PassengerFullName = "Glenna Windler",
                            PassengerPassport = "WZKSVMB84",
                            Place = "H84",
                            Price = 969.14m
                        },
                        new
                        {
                            Id = 66,
                            BuyDate = new DateTime(2021, 4, 5, 1, 10, 42, 387, DateTimeKind.Local).AddTicks(2297),
                            IsActive = false,
                            Number = "WBAHZ85",
                            PassengerFullName = "Donny Balistreri",
                            PassengerPassport = "OKZURFI85",
                            Place = "H85",
                            Price = 264.82m
                        },
                        new
                        {
                            Id = 67,
                            BuyDate = new DateTime(2021, 1, 13, 14, 56, 26, 106, DateTimeKind.Local).AddTicks(7311),
                            IsActive = false,
                            Number = "BBVJG86",
                            PassengerFullName = "Aurelia Jakubowski",
                            PassengerPassport = "VICZTBH86",
                            Place = "L86",
                            Price = 333.59m
                        },
                        new
                        {
                            Id = 68,
                            BuyDate = new DateTime(2021, 1, 27, 10, 8, 33, 164, DateTimeKind.Local).AddTicks(5128),
                            IsActive = false,
                            Number = "HCTKY87",
                            PassengerFullName = "Moshe Mohr",
                            PassengerPassport = "NAKZBAI87",
                            Place = "J87",
                            Price = 758.27m
                        },
                        new
                        {
                            Id = 69,
                            BuyDate = new DateTime(2021, 1, 10, 15, 43, 7, 384, DateTimeKind.Local).AddTicks(8300),
                            IsActive = false,
                            Number = "UVOGC88",
                            PassengerFullName = "Loma Von",
                            PassengerPassport = "IEXOBXH88",
                            Place = "I88",
                            Price = 13.44m
                        },
                        new
                        {
                            Id = 70,
                            BuyDate = new DateTime(2021, 1, 14, 18, 33, 45, 827, DateTimeKind.Local).AddTicks(4606),
                            IsActive = true,
                            Number = "UDULV89",
                            PassengerFullName = "Annabel Bechtelar",
                            PassengerPassport = "OHXOSUT89",
                            Place = "F89",
                            Price = 577.93m
                        },
                        new
                        {
                            Id = 71,
                            BuyDate = new DateTime(2021, 9, 6, 16, 25, 41, 563, DateTimeKind.Local).AddTicks(3106),
                            IsActive = false,
                            Number = "QTNGQ90",
                            PassengerFullName = "Aliza Fisher",
                            PassengerPassport = "TTZRBOZ90",
                            Place = "F90",
                            Price = 410.66m
                        },
                        new
                        {
                            Id = 72,
                            BuyDate = new DateTime(2021, 8, 17, 8, 47, 23, 721, DateTimeKind.Local).AddTicks(6578),
                            IsActive = true,
                            Number = "GDTXH91",
                            PassengerFullName = "Jakayla Leannon",
                            PassengerPassport = "PIUJPJA91",
                            Place = "K91",
                            Price = 330.11m
                        },
                        new
                        {
                            Id = 73,
                            BuyDate = new DateTime(2021, 2, 7, 5, 20, 32, 932, DateTimeKind.Local).AddTicks(3401),
                            IsActive = false,
                            Number = "EBQXA92",
                            PassengerFullName = "Bradford Ledner",
                            PassengerPassport = "NVJXYFQ92",
                            Place = "A92",
                            Price = 344.77m
                        },
                        new
                        {
                            Id = 74,
                            BuyDate = new DateTime(2021, 9, 28, 6, 52, 29, 153, DateTimeKind.Local).AddTicks(5952),
                            IsActive = false,
                            Number = "INHQZ93",
                            PassengerFullName = "Cecil White",
                            PassengerPassport = "UKVMYWT93",
                            Place = "G93",
                            Price = 381.84m
                        },
                        new
                        {
                            Id = 75,
                            BuyDate = new DateTime(2021, 8, 22, 22, 47, 53, 904, DateTimeKind.Local).AddTicks(6398),
                            IsActive = false,
                            Number = "VJRDI94",
                            PassengerFullName = "Ansley Stoltenberg",
                            PassengerPassport = "EUKTBXD94",
                            Place = "K94",
                            Price = 800.65m
                        },
                        new
                        {
                            Id = 76,
                            BuyDate = new DateTime(2020, 12, 12, 23, 8, 1, 90, DateTimeKind.Local).AddTicks(80),
                            IsActive = true,
                            Number = "SGQBT95",
                            PassengerFullName = "Aglae Haley",
                            PassengerPassport = "LGJRIUC95",
                            Place = "K95",
                            Price = 733.79m
                        },
                        new
                        {
                            Id = 77,
                            BuyDate = new DateTime(2020, 12, 16, 13, 38, 53, 335, DateTimeKind.Local).AddTicks(5793),
                            IsActive = true,
                            Number = "HCTSD96",
                            PassengerFullName = "Marques Grady",
                            PassengerPassport = "AAOHAZM96",
                            Place = "E96",
                            Price = 877.57m
                        },
                        new
                        {
                            Id = 78,
                            BuyDate = new DateTime(2021, 8, 1, 18, 27, 51, 912, DateTimeKind.Local).AddTicks(5637),
                            IsActive = false,
                            Number = "DOPPU97",
                            PassengerFullName = "Monserrat Christiansen",
                            PassengerPassport = "CHADBPI97",
                            Place = "E97",
                            Price = 125.37m
                        },
                        new
                        {
                            Id = 79,
                            BuyDate = new DateTime(2021, 6, 14, 14, 34, 51, 121, DateTimeKind.Local).AddTicks(727),
                            IsActive = false,
                            Number = "WWNKY98",
                            PassengerFullName = "Adelbert Rowe",
                            PassengerPassport = "SOJXIAC98",
                            Place = "H98",
                            Price = 992.14m
                        },
                        new
                        {
                            Id = 80,
                            BuyDate = new DateTime(2021, 8, 17, 7, 57, 22, 736, DateTimeKind.Local).AddTicks(1375),
                            IsActive = true,
                            Number = "MQOTN99",
                            PassengerFullName = "Brannon Spinka",
                            PassengerPassport = "TYODRTE99",
                            Place = "H99",
                            Price = 502.17m
                        },
                        new
                        {
                            Id = 81,
                            BuyDate = new DateTime(2020, 11, 18, 2, 3, 46, 340, DateTimeKind.Local).AddTicks(2242),
                            IsActive = false,
                            Number = "NPQBW100",
                            PassengerFullName = "Ashtyn Spinka",
                            PassengerPassport = "PPIDEDY100",
                            Place = "L100",
                            Price = 703.52m
                        },
                        new
                        {
                            Id = 82,
                            BuyDate = new DateTime(2021, 1, 24, 12, 1, 3, 266, DateTimeKind.Local).AddTicks(8503),
                            IsActive = false,
                            Number = "XBFRD101",
                            PassengerFullName = "Garrison Cummings",
                            PassengerPassport = "PFRPBFR101",
                            Place = "K101",
                            Price = 36.20m
                        },
                        new
                        {
                            Id = 83,
                            BuyDate = new DateTime(2021, 2, 19, 0, 13, 50, 468, DateTimeKind.Local).AddTicks(8177),
                            IsActive = false,
                            Number = "SOLMI102",
                            PassengerFullName = "Jeremy Murphy",
                            PassengerPassport = "VXCBIUV102",
                            Place = "D102",
                            Price = 433.64m
                        },
                        new
                        {
                            Id = 84,
                            BuyDate = new DateTime(2021, 7, 8, 14, 56, 8, 341, DateTimeKind.Local).AddTicks(2897),
                            IsActive = false,
                            Number = "PLMSB103",
                            PassengerFullName = "Keshawn Beahan",
                            PassengerPassport = "VQRBZSM103",
                            Place = "F103",
                            Price = 934.82m
                        },
                        new
                        {
                            Id = 85,
                            BuyDate = new DateTime(2021, 10, 11, 18, 25, 30, 207, DateTimeKind.Local).AddTicks(7322),
                            IsActive = true,
                            Number = "EHSFL104",
                            PassengerFullName = "Eldora Renner",
                            PassengerPassport = "XHIKGEM104",
                            Place = "E104",
                            Price = 461.53m
                        },
                        new
                        {
                            Id = 86,
                            BuyDate = new DateTime(2021, 8, 30, 11, 56, 19, 165, DateTimeKind.Local).AddTicks(2932),
                            IsActive = true,
                            Number = "GABGV105",
                            PassengerFullName = "Claude Dare",
                            PassengerPassport = "PJIOTWS105",
                            Place = "I105",
                            Price = 26.13m
                        },
                        new
                        {
                            Id = 87,
                            BuyDate = new DateTime(2021, 10, 5, 7, 26, 44, 807, DateTimeKind.Local).AddTicks(6860),
                            IsActive = true,
                            Number = "QEGJG106",
                            PassengerFullName = "Grant Frami",
                            PassengerPassport = "QVNNNNW106",
                            Place = "B106",
                            Price = 613.16m
                        },
                        new
                        {
                            Id = 88,
                            BuyDate = new DateTime(2021, 4, 20, 22, 7, 6, 39, DateTimeKind.Local).AddTicks(7203),
                            IsActive = true,
                            Number = "PIXNF107",
                            PassengerFullName = "Leo Corkery",
                            PassengerPassport = "EAXKIRI107",
                            Place = "H107",
                            Price = 469.58m
                        },
                        new
                        {
                            Id = 89,
                            BuyDate = new DateTime(2021, 3, 26, 16, 59, 1, 559, DateTimeKind.Local).AddTicks(8417),
                            IsActive = true,
                            Number = "RIYBM108",
                            PassengerFullName = "Robyn Bartell",
                            PassengerPassport = "EPVKVPF108",
                            Place = "C108",
                            Price = 195.54m
                        },
                        new
                        {
                            Id = 90,
                            BuyDate = new DateTime(2021, 1, 17, 5, 30, 9, 924, DateTimeKind.Local).AddTicks(4732),
                            IsActive = false,
                            Number = "XOCWA109",
                            PassengerFullName = "Alison Emmerich",
                            PassengerPassport = "FABBBGF109",
                            Place = "D109",
                            Price = 607.86m
                        },
                        new
                        {
                            Id = 91,
                            BuyDate = new DateTime(2021, 4, 13, 5, 55, 41, 119, DateTimeKind.Local).AddTicks(9966),
                            IsActive = false,
                            Number = "FALQF110",
                            PassengerFullName = "Zachariah Hilpert",
                            PassengerPassport = "KADFTOZ110",
                            Place = "K110",
                            Price = 464.21m
                        },
                        new
                        {
                            Id = 92,
                            BuyDate = new DateTime(2021, 2, 9, 1, 44, 54, 97, DateTimeKind.Local).AddTicks(516),
                            IsActive = false,
                            Number = "VBQES111",
                            PassengerFullName = "Leone Huels",
                            PassengerPassport = "THLBDIN111",
                            Place = "F111",
                            Price = 492.36m
                        },
                        new
                        {
                            Id = 93,
                            BuyDate = new DateTime(2021, 1, 8, 0, 41, 2, 593, DateTimeKind.Local).AddTicks(5367),
                            IsActive = false,
                            Number = "ZHHGB112",
                            PassengerFullName = "Jaren Hermiston",
                            PassengerPassport = "IUYDROT112",
                            Place = "K112",
                            Price = 835.21m
                        },
                        new
                        {
                            Id = 94,
                            BuyDate = new DateTime(2020, 12, 7, 17, 23, 49, 245, DateTimeKind.Local).AddTicks(1531),
                            IsActive = false,
                            Number = "UWHCK113",
                            PassengerFullName = "Ella Jakubowski",
                            PassengerPassport = "HVLJAWL113",
                            Place = "G113",
                            Price = 129.71m
                        },
                        new
                        {
                            Id = 95,
                            BuyDate = new DateTime(2021, 8, 11, 18, 11, 35, 89, DateTimeKind.Local).AddTicks(2939),
                            IsActive = false,
                            Number = "NMDOZ114",
                            PassengerFullName = "Isac Zieme",
                            PassengerPassport = "UAXVEJD114",
                            Place = "G114",
                            Price = 217.56m
                        },
                        new
                        {
                            Id = 96,
                            BuyDate = new DateTime(2021, 8, 18, 22, 33, 25, 263, DateTimeKind.Local).AddTicks(8878),
                            IsActive = false,
                            Number = "IGFDV115",
                            PassengerFullName = "Winona Christiansen",
                            PassengerPassport = "BIGFSDR115",
                            Place = "I115",
                            Price = 223.26m
                        },
                        new
                        {
                            Id = 97,
                            BuyDate = new DateTime(2021, 4, 18, 5, 57, 44, 958, DateTimeKind.Local).AddTicks(2634),
                            IsActive = true,
                            Number = "AGHVA116",
                            PassengerFullName = "Donnie Connelly",
                            PassengerPassport = "IAYKITG116",
                            Place = "K116",
                            Price = 917.31m
                        },
                        new
                        {
                            Id = 98,
                            BuyDate = new DateTime(2020, 11, 22, 23, 19, 4, 23, DateTimeKind.Local).AddTicks(5536),
                            IsActive = true,
                            Number = "CDVAA117",
                            PassengerFullName = "Rodrick Weber",
                            PassengerPassport = "VUDPIUH117",
                            Place = "I117",
                            Price = 433.47m
                        },
                        new
                        {
                            Id = 99,
                            BuyDate = new DateTime(2021, 6, 22, 6, 27, 35, 106, DateTimeKind.Local).AddTicks(5049),
                            IsActive = false,
                            Number = "EHFZT118",
                            PassengerFullName = "Lelia VonRueden",
                            PassengerPassport = "DJACTFD118",
                            Place = "K118",
                            Price = 782.85m
                        },
                        new
                        {
                            Id = 100,
                            BuyDate = new DateTime(2021, 8, 21, 13, 50, 22, 711, DateTimeKind.Local).AddTicks(8780),
                            IsActive = true,
                            Number = "CVJIT119",
                            PassengerFullName = "Kelley Parisian",
                            PassengerPassport = "FMORXOH119",
                            Place = "E119",
                            Price = 323.89m
                        });
                });

            modelBuilder.Entity("Airport.Data.Entities.FlightTicket", b =>
                {
                    b.HasOne("Airport.Data.Entities.Flight", "Flight")
                        .WithMany("FlightTickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airport.Data.Entities.Ticket", "Ticket")
                        .WithOne("FlightTicket")
                        .HasForeignKey("Airport.Data.Entities.FlightTicket", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Airport.Data.Entities.Flight", b =>
                {
                    b.Navigation("FlightTickets");
                });

            modelBuilder.Entity("Airport.Data.Entities.Ticket", b =>
                {
                    b.Navigation("FlightTicket");
                });
#pragma warning restore 612, 618
        }
    }
}
